// <auto-generated />
namespace Switch.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datachanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datachanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201509281205251_data-changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
